##
## Author(s):
##  - Cedric GESTES      <gestes@aldebaran-robotics.com>
##
## Copyright (C) 2011 Aldebaran Robotics
##

include $(GOROOT)/src/Make.inc

TARG=test
GOFILES=test.go

include $(GOROOT)/src/Make.cmd
